name: Bootstrap
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::649534857523:role/github-ci
          aws-region: ${{ vars.AWS_REGION }}

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.local/share/pnpm/store/v3
          key: cargo-pnpm-build-cache

      - run: nix develop -c pnpm --prefix=infra install

      - run: nix develop -c cargo clippy
      - run: nix develop -c just deploy
